"""dnsdist backend config exporter."""

from __future__ import annotations

from pathlib import Path

from resolver_inventory.models import ValidationResult

_HEADER = """\
-- Generated by resolver-inventory
-- Do NOT edit by hand; re-run: resolver-inventory export dnsdist
"""


def _dns_backend(host: str, port: int, provider: str | None) -> str:
    comment = f"  -- {provider}" if provider else ""
    return f'newServer({{address="{host}:{port}", checkName="dns.msftncsi.com."}}){comment}'


def _doh_backend(result: ValidationResult) -> str:
    c = result.candidate
    url = c.endpoint_url or f"https://{c.host}:{c.port}{c.path or '/dns-query'}"
    sni = c.tls_server_name or c.host
    path = c.path or "/dns-query"
    provider = c.provider or ""
    lines = [
        "newServer({",
        f'  address="{c.host}:{c.port}",',
        '  tls="openssl",',
        f'  subjectName="{sni}",',
        f'  dohPath="{path}",',
        "  validateCertificates=true,",
        '  checkName="dns.msftncsi.com.",',
        f"  -- url: {url}",
    ]
    if provider:
        lines.append(f"  -- provider: {provider}")
    lines.append("})")
    return "\n".join(lines)


def export_dnsdist(
    results: list[ValidationResult],
    *,
    accepted_only: bool = True,
    path: str | Path | None = None,
) -> str:
    """Render a dnsdist backend configuration snippet.

    Only includes classic DNS and DoH backends separately.
    Returns the config text. If *path* is given, also writes it to disk.
    """
    records = [r for r in results if r.accepted] if accepted_only else results

    dns_lines: list[str] = []
    doh_lines: list[str] = []

    for r in records:
        c = r.candidate
        if c.transport in ("dns-udp", "dns-tcp"):
            dns_lines.append(_dns_backend(c.host, c.port, c.provider))
        elif c.transport == "doh":
            doh_lines.append(_doh_backend(r))

    sections: list[str] = [_HEADER]
    if dns_lines:
        sections.append("-- Plain DNS backends")
        sections.extend(dns_lines)
        sections.append("")
    if doh_lines:
        sections.append("-- DoH backends")
        sections.extend(doh_lines)
        sections.append("")

    text = "\n".join(sections)
    if path is not None:
        out = Path(path)
        out.parent.mkdir(parents=True, exist_ok=True)
        out.write_text(text, encoding="utf-8")
    return text
