"""Unbound forward-zone config exporter.

Only emits classic DNS forwarders that passed plain DNS validation.
Unbound is not health-aware in the same way dnsdist is; this exporter
is intentionally conservative.
"""

from __future__ import annotations

from pathlib import Path

from resolver_inventory.models import ValidationResult

_HEADER = """\
# Generated by resolver-inventory
# Do NOT edit by hand; re-run: resolver-inventory export unbound
"""


def export_unbound(
    results: list[ValidationResult],
    *,
    accepted_only: bool = True,
    forward_zone: str = ".",
    path: str | Path | None = None,
) -> str:
    """Render an Unbound forward-zone configuration snippet.

    Only includes plain DNS (UDP/TCP) accepted resolvers.
    Returns the config text. If *path* is given, also writes it to disk.
    """
    records = [r for r in results if r.accepted] if accepted_only else results

    seen_hosts: set[str] = set()
    forward_addrs: list[str] = []
    for r in records:
        c = r.candidate
        if c.transport not in ("dns-udp", "dns-tcp"):
            continue
        host_key = c.host
        if host_key in seen_hosts:
            continue
        seen_hosts.add(host_key)
        addr = f"{c.host}@{c.port}" if c.port != 53 else c.host
        forward_addrs.append(f"    forward-addr: {addr}")

    lines = [_HEADER, "forward-zone:"]
    lines.append(f'    name: "{forward_zone}"')
    lines.extend(forward_addrs)
    lines.append("")

    text = "\n".join(lines)
    if path is not None:
        out = Path(path)
        out.parent.mkdir(parents=True, exist_ok=True)
        out.write_text(text, encoding="utf-8")
    return text
